services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db_data:/data/db
  mongodb-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
  frontend: 
    image: ashmit1020/my_app:v.1.1
    ports:
      - 2002:80
  backend:
    image: ashmit1020/my_api:v.1.0
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/User_acc?authSource=admin
      PORT: 3000
    depends_on:
        - mongodb
volumes:
  db_data: 
    driver: local