services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongodb-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
  frontend: 
    image: my_app
    ports:
      - 2002:80
  backend:
    image: my_api
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/User_acc?authSource=admin
      PORT: 3000
    depends_on:
        - mongodb